language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
before_install:
- npm config set spin false
- npm install -g bower phantomjs-prebuilt
- bower --version
- phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ZSEdsOaNhkgWBsXliHPIwyqNxvnIzZQnNHWVAGVc8W4+i9cHPR20sAIAXwNa5TMtPmb/1yIussMoc8+1efIIBsy+mam07isy3FWLjLqTuyU/nBhJ3FdoDlALXPG5Yp2mnKK1SzFtxI4SqboIK0spptzsiih1C8qFkdraVBVJoOGeF/vgz2lcbVffC58SR/rXTK7p8tpvzEfxCMfruFvBZu2D34AI27T6cSBm/IGD14XCXl+l83PevWQZTVZz2gAo30dZoQ5DsJ6gSucM/F67+9U9uD0aETPNR7N/8gA70KJ7KqJERqYadSIzF/JwccxyG8gnWkagKduGSyQaZ6IdUDc4acpz6fkCkueF0AdtwP5u0FyaPq/dHbkVGRI752IRCyJjHVCqBVBdgrT72FyB1Q+gz/JaEI7scW46RIkwsu8dBV1URT1XI+dYGVku2qlrUZ37smVpTmypGeLCuCg5u8fETkpUGZqyyPCVaK4Zv0ta2CaFNCEccAX3UiZhlhKS3hYYVMW6lEwCH4zfsUAk0Cy7fYYUF7q6VRcYK3LR2R5qnAvkgAf3a5c+C0+lYPgvw89klQvqu7a3eMcFD2rfcXfflMzUvKfFKENhPp0Cpop0Xj0w5qodMKYDprpHjo7UL3JMWIqtpE/Z8sTontEaKPgn+R/b9gfTtMzQY7XvZiY=
  app: vast-journey-17491
  on:
    repo: scudco/ember-commently
